{{- if and .Values.enterprise.enabled .Values.enterprise.auditTrail.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cased-cd.fullname" . }}-enterprise-audit
  labels:
    {{- include "cased-cd.labels" . | nindent 4 }}
    app.kubernetes.io/component: enterprise
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.enterprise.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.enterprise.persistence.size }}
{{- end }}
