{{- if .Values.rbacProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cased-cd.fullname" . }}-rbac-proxy
  labels:
    {{- include "cased-cd.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac-proxy
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cased-cd.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rbac-proxy
{{- end }}
