{{- if .Values.rbacProxy.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cased-cd.fullname" . }}-audit-logs
  labels:
    {{- include "cased-cd.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac-proxy
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.rbacProxy.persistence.storageClass }}
  storageClassName: {{ .Values.rbacProxy.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.rbacProxy.persistence.size }}
{{- end }}
